name: Docker Image CD

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag zekro/tokentools:latest
    - name: Publish the Docker image
      run: |
        docker login -u zekro -p ${{ secrets.DOCKER_PASSWORD }}
        docker push zekro/tokentools:latest
